---
apiVersion: v1
kind: Service
metadata:
    name: ehc586-test-flask-service
    labels:
        username: ehc586
        env: test
spec:
    type: ClusterIP
    selector:
        app: ehc586-test-flask
    ports:
    - name: ehc586-test-flask
      port: 5000
      targetPort: 5000
