---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ehc586-test-redis
    labels:
        username: ehc586
        env: test
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: nfs
    resources:
        requests:
            storage: 1Gi
