---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ehc586-test-redis-deployment
    labels:
        username: ehc586
        env: test
        app: ehc586-test-redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ehc586-test-redis
    template:
        metadata:
            labels:
                app: ehc586-test-redis
        spec:
            containers:
                - name: ehc586-test-redis-deployment
                  imagePullPolicy: Always
                  image: redis:6
                  ports:
                  - name: http
                    containerPort: 6379
                  volumeMounts:
                  - name: ehc586-test-redis
                    mountPath: "/data"
            volumes:
            - name: ehc586-test-redis
              persistentVolumeClaim:
                  claimName: ehc586-test-redis
